nelmio_cors:
    defaults:
        allow_credentials: false
        origin_regex: false
        allow_origin: []
        allow_methods: []
        allow_headers: []
        expose_headers: []
        max_age: 0
        hosts: []
        forced_allow_origin_value: ~
    paths:
        '^/api/v1/netBS':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'POST']
            max_age: 3600