version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.php.dev
    ports: 
      - 80:80
    volumes:
      - .:/var/www/html
  
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: netbs
      MARIADB_DATABASE: netbs5
      MARIADB_USER: root
      MARIADB_PASSWORD: root
    volumes:
      - ./docker/dump:/docker-entrypoint-initdb.d
      - ./docker/data:/var/lib/mysql:Z
    ports:
      - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: netbs