controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /netBS/bs

api_controllers:
    resource: ../../src/ApiController/
    type: annotation
    prefix: /

kernel:
    resource: ../../src/Kernel.php
    type: annotation
