services:
    _defaults:
        autowire: true
        autoconfigure: true

    NetBS\CoreBundle\Voter\DynamicListVoter:
        tags:
            - { name: security.voter }

    NetBS\CoreBundle\Voter\ParameterVoter:
        tags:
            - { name: security.voter }

    NetBS\CoreBundle\Voter\ExportConfigurationVoter:
        tags:
            - { name: security.voter }

    NetBS\CoreBundle\Voter\NewsVoter:
        tags:
            - { name: security.voter }
