doctrine:
  orm:
    auto_mapping: true
    metadata_cache_driver:
      type: pool
      pool: doctrine.metadata_cache_pool
    result_cache_driver:
      type: pool
      pool: doctrine.result_cache_pool
    query_cache_driver:
      type: pool
      pool: doctrine.query_cache_pool

framework:
  cache:
    pools:
      doctrine.result_cache_pool:
        adapter: cache.app
      doctrine.metadata_cache_pool:
        adapter: cache.app
      doctrine.query_cache_pool:
        adapter: cache.app