framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    # Set by supervisor directly
                    consumer: '%env(MESSENGER_CONSUMER_NAME)%'
            failed:
                dsn: 'doctrine://default?queue_name=failed'

        routing:
            'App\Message\NextcloudGroupNotification': async
