framework:
    messenger:
        failure_transport: failed

        transports:
            groupsync:
                dsn: 'doctrine://default?queue_name=groupsync'
            talkbot:
                dsn: 'doctrine://default?queue_name=talkbot'
            failed:
                dsn: 'doctrine://default?queue_name=failed'

        routing:
            'App\Message\NextcloudGroupNotification': groupsync
            'App\Message\NewsNotification': talkbot
