# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Automatics\:
        resource: '../src/Automatics/'
        tags: ['netbs.list.model', 'netbs.automatic_list']

    App\ListModel\:
        resource: '../src/ListModel/'
        tags: ['netbs.list.model']

    App\Searcher\:
        resource: '../src/Searcher/'
        tags: ['netbs.list.model', 'netbs.searcher']

    App\Binder\:
        resource: '../src/Binder/'
        tags: ['netbs.searcher.binder']

    App\ApiController\:
        resource: '../src/ApiController/'
        tags: ['controller.service_arguments']

    App\Serializer\:
        resource: '../src/Serializer/'
        tags: ['serializer.normalizer']

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']


    App\Serializer\MediaNormalizer:
        arguments:
            $webPath: '%env(GALERIE_WEBPATH)%'
            $extension: "@twig.extension.assets"

imports:
    - { resource: "@NetBSCoreBundle/Resources/config/services.yml" }
    - { resource: "@NetBSFichierBundle/Resources/config/services.yml" }
    - { resource: "@NetBSSecureBundle/Resources/config/services.yml" }
    - { resource: "@NetBSListBundle/Resources/config/services.yml" }
    - { resource: "@OvescoFacturationBundle/Resources/config/services.yml" }
